export const sampleProjects = [
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 1,
    title: "inbox",
    is_public: false,
    is_archive: false,
    description: "inbox",
    action_plan: "inbox",
    state: "doing",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 1,
    review: "text",
    created_at: "2023-03-01 12:31:21",
    updated_at: "2023-03-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 2,
    title: "W)ProcPerf",
    is_public: false,
    is_archive: false,
    description: "ProcPerf",
    action_plan: "アクションプランテスト",
    state: "done",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 1,
    review: "text",
    created_at: "2023-03-01 12:31:21",
    updated_at: "2023-03-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 3,
    title: "W)fvqs",
    is_public: false,
    is_archive: false,
    description: "fvqs",
    action_plan: "fvqsアクションプランテスト",
    state: "nodone",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 1,
    review: "doing",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 4,
    title: "W)QstoreView",
    is_public: true,
    is_archive: true,
    description: "fvqs",
    action_plan: "fvqsアクションプランテスト",
    state: "nodone",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 2,
    review: "doing",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 5,
    title: "W)IM-Review",
    is_public: false,
    is_archive: false,
    description: "IM-Review",
    action_plan: "準備すること",
    state: "nodone",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 5,
    review: "doing",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 6,
    title: "eel to tuna devdb",
    is_public: false,
    is_archive: true,
    description:
      "1)移行手順の計画とドキュメンテーション 2)新しい環境でのインフラストラクチャの設定 3)データのバックアップと転送 4)テスト環境での詳細な検証 5)本番環境への切り替えと監視。",
    action_plan: "サーバー周り準備すること",
    state: "nodone",
    from_date: "2023-07-01",
    to_date: "2023-07-10",
    important: 1,
    review: "notdo",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 7,
    title: "Lgtd",
    is_public: false,
    is_archive: true,
    description:
      "LocalGTD：自分用のGTDの作成。個人認証、個人特定しての情報の管理はできること",
    action_plan: "ひとまずモックアップの作成",
    state: "doing",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 8,
    title: "MixViewer",
    is_public: false,
    is_archive: true,
    description: "Mix情報の可視化",
    action_plan: "役割完了",
    state: "done",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 9,
    title: "kangEPR",
    is_public: false,
    is_archive: true,
    description: "CareEKarte",
    action_plan: "",
    state: "done",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 19,
    title: "クラウドインフラの構築",
    is_public: false,
    is_archive: true,
    description: "クラウドインフラの構築",
    action_plan: "",
    state: "done",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 20,
    title: "データセンターの設計と運用",
    is_public: false,
    is_archive: true,
    description: "データセンターの設計と運用",
    action_plan: "",
    state: "done",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 21,
    title: "自動化されたデプロイとプロビジョニングの実装",
    is_public: false,
    is_archive: true,
    description:
      "効率的な空調設備や電源管理システム、物理セキュリティ対策などが重要です。また、監視・管理システムの導入や定期的なメンテナンスなども欠かせません。最近では、クラウド環境への移行なども注目されています。",
    action_plan: "",
    state: "done",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 31,
    title: "スケーラブルなシステムの監視と保守",
    is_public: false,
    is_archive: true,
    description: `モニタリングツールを導入する
    /アラートと通知の設定
    /ログ収集と分析
    /監視システムの改善
    /障害対応プロセスの整備`,
    action_plan: "",
    state: "done",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
];

export const sampleTasks = [
  {
    id: 1,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "新しい機能を実装する",
    action_plan: "設計書を作成して、コードを書く",
    detail: "新しい機能を実装する",
    start_date: "2023-06-11",
    due_date: "2023-06-19",
    state: "doing",
    type: "soon",
    review: "",
  },
  {
    id: 2,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "	「ドキュメントをレビューする」",
    action_plan: "	「ドキュメントの内容をチェックする」	",
    detail: "「ドキュメントをレビューする」	",
    start_date: "2023-06-16",
    due_date: "2023-06-23",
    state: "waiting",
    type: "waiting",
    review: "",
  },
  {
    id: 3,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "	バグを修正する",
    action_plan: "バグの報告書を読んで、コードを修正する",
    detail: "	バグを修正する",
    start_date: "2023-06-12",
    due_date: "2023-06-17",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 4,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "	ドキュメントを更新する",
    action_plan: "ドキュメントを更新する",
    detail: "ドキュメントを更新する",
    start_date: "2023-06-13",
    due_date: "2023-06-20",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 5,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "	「新しいテストケースを作成する」	",
    action_plan: "	「テストケースの設計書を作成して、コードを書く」	",
    detail: "「新しいテストケースを作成する」",
    start_date: "2023-06-14",
    due_date: "2023-06-21",
    state: "doing",
    type: "soon",
    review: "",
  },
  {
    id: 6,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "バグをテストする",
    action_plan: "バグのテストケースを実行する",
    detail: "バグをテストする	",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 7,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "新しい機能をデプロイする",
    action_plan: "新しい機能をサーバーへデプロイする",
    detail: "新しい機能をデプロイする",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },

  //   id	user_id	project_id	is_private	is_archive	title	action_plan	detail	start_date	due_date	state	type	review
  // 7	7	7	false	false	「コードをレビューする」	「コードの内容をチェックする」	「コードをレビューする」	2023-06-17	2023-06-24	doing	soon
  // 9	9	9	false	false	「バグを修正してデプロイする」	「バグの修正をサーバーへデプロイする」	「バグを修正してデプロイする」	2023-06-19	2023-06-26	waiting	waiting
];
