export const sampleProjects = [
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 1,
    title: "inbox",
    is_public: false,
    is_archive: false,
    description: "inbox",
    action_plan: "inbox",
    state: "doing",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 1,
    review: "text",
    created_at: "2023-03-01 12:31:21",
    updated_at: "2023-03-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 2,
    title: "W)ProcPerf",
    is_public: false,
    is_archive: false,
    description: "ProcPerf",
    action_plan: "アクションプランテスト",
    state: "done",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 1,
    review: "text",
    created_at: "2023-03-01 12:31:21",
    updated_at: "2023-03-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 4,
    title: "ProcPerf作成",
    is_public: true,
    is_archive: true,
    description: "fvqs",
    action_plan: "fvqsアクションプランテスト",
    state: "nodone",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 2,
    review: "doing",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 5,
    title: "Lgtdv1",
    is_public: false,
    is_archive: false,
    description: "IM-Review",
    action_plan: "準備すること",
    state: "nodone",
    from_date: "2023-05-01",
    to_date: "2023-06-01",
    important: 5,
    review: "doing",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 6,
    title: "eel to tuna devdb",
    is_public: false,
    is_archive: true,
    description:
      "1)移行手順の計画とドキュメンテーション 2)新しい環境でのインフラストラクチャの設定 3)データのバックアップと転送 4)テスト環境での詳細な検証 5)本番環境への切り替えと監視。",
    action_plan: "サーバー周り準備すること",
    state: "nodone",
    from_date: "2023-07-01",
    to_date: "2023-07-10",
    important: 1,
    review: "notdo",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
  {
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    id: 7,
    title: "Lgtd",
    is_public: false,
    is_archive: true,
    description:
      "LocalGTD：自分用のGTDの作成。個人認証、個人特定しての情報の管理はできること",
    action_plan: "ひとまずモックアップの作成",
    state: "doing",
    from_date: "2023-06-01",
    to_date: "",
    important: 1,
    review: "",
    created_at: "2023-04-01 12:31:21",
    updated_at: "2023-04-01 12:31:21",
  },
];

export const sampleTasks = [
  {
    id: 1,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "導入 IN 情報表示",
    action_plan: "導入 IN 情報表示",
    detail: "導入 IN 情報表示",
    start_date: "2023-06-11",
    due_date: "2023-06-19",
    state: "doing",
    type: "soon",
    review: "",
  },
  {
    id: 2,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "OPM9 時での CPU をローカルに保存",
    action_plan: "OPM9 時での CPU をローカルに保存",
    detail: "OPM9 時での CPU をローカルに保存",
    start_date: "2023-06-16",
    due_date: "2023-06-23",
    state: "waiting",
    type: "waiting",
    review: "",
  },
  {
    id: 3,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "OPM9 時での CPU 表示",
    action_plan: "OPM9 時での CPU 表示",
    detail: "OPM9 時での CPU 表示",
    start_date: "2023-06-12",
    due_date: "2023-06-17",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 4,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "SSILOGF ９時で Distinct 数の表示",
    action_plan: "SSILOGF ９時で Distinct 数の表示",
    detail: "SSILOGF ９時で Distinct 数の表示",
    start_date: "2023-06-13",
    due_date: "2023-06-20",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 5,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "各々 Avg7Top5 での情報表示",
    action_plan: "各々 Avg7Top5 での情報表示",
    detail: "各々 Avg7Top5 での情報表示",
    start_date: "2023-06-14",
    due_date: "2023-06-21",
    state: "doing",
    type: "soon",
    review: "",
  },
  {
    id: 6,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "画面作成（DataTabeJS の利用でなく、BootGrid・列選択機能）",
    action_plan: "画面作成（DataTabeJS の利用でなく、BootGrid・列選択機能）",
    detail: "画面作成（DataTabeJS の利用でなく、BootGrid・列選択機能）",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 7,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 2,
    is_public: false,
    is_archive: false,
    title: "CSV 保存ボタン作成",
    action_plan: "CSV 保存ボタン作成",
    detail: "CSV 保存ボタン作成",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },

  {
    id: 41,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 4,
    is_public: false,
    is_archive: false,
    title: "取り込み処理最適化",
    action_plan: "取り込み処理最適化",
    detail: "取り込み処理最適化",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 51,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "UI モックアップ作成",
    action_plan: "UI モックアップ作成",
    detail: "UI モックアップ作成",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 52,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "GitHubUp",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 53,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "VercelUp",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 54,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "テーブル作成",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 55,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "UI 調整、タスクからプロジェクトへ",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 56,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "UI 各種フォームからのコミット処理",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 57,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "UI フォーム　タスク・プロジェクト選べるように",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 58,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 5,
    is_public: false,
    is_archive: false,
    title: "Bizlogic で DB と UI 繋げる、DB はダミーで OK",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 101,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "日報を作成する",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 102,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "Notion見る",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },
  {
    id: 103,
    user_id: "xxxxxxxxxxxx-xxxxxxx",
    project_id: 1,
    is_public: false,
    is_archive: false,
    title: "Keepの整理",
    action_plan: "",
    detail: "",
    start_date: "2023-06-15",
    due_date: "2023-06-22",
    state: "done",
    type: "done",
    review: "",
  },

  //   id	user_id	project_id	is_private	is_archive	title	action_plan	detail	start_date	due_date	state	type	review
  // 7	7	7	false	false	「コードをレビューする」	「コードの内容をチェックする」	「コードをレビューする」	2023-06-17	2023-06-24	doing	soon
  // 9	9	9	false	false	「バグを修正してデプロイする」	「バグの修正をサーバーへデプロイする」	「バグを修正してデプロイする」	2023-06-19	2023-06-26	waiting	waiting
];
